name: Publish to npm

on:
  push:
    branches: [main]

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint, Type Check, Build
        run: |
          bun run lint
          bunx tsc --noEmit
          bun run build

      - name: Authenticate & Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          bun run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
