name: Publish to GitHub Packages

on:
  push:
    branches: [main]

jobs:
  publish-github:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint, Type Check, Build
        run: |
          bun run lint
          bunx tsc --noEmit
          bun run build

      - name: Authenticate & Publish to GitHub Package Registry
        run: |
          echo "@sandeep-jaiswar:registry=https://npm.pkg.github.com/" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${GH_PUBLISH_TOKEN}" >> ~/.npmrc
          bun run release
        env:
          GH_PUBLISH_TOKEN: ${{ secrets.GH_PUBLISH_TOKEN }}
